id: I21622562
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:35:27+00:00'
last_modified: '2022-06-09T07:04:40.839769+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20433
  title: ཁྱད་དུ་འཕགས་པའི་བྱང་ཐང་ངོ་མཚར་འོས་པའི་ཐོན་ཁུངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DDD7:
      image_group_id: I1GS53491
      title: Volume 1 of khyad du 'phags pa'i byang thang ngo mtshar 'os pa'i thon
        khungs
      total_pages: 187
      order: 1
      base_file: DDD7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
