id: P007887
initial_creation_type: ocr
source_metadata:
  id: bdr:W20433
  title: ཁྱད་དུ་འཕགས་པའི་བྱང་ཐང་ངོ་མཚར་འོས་པའི་ཐོན་ཁུངས
  author: ''
  volumes:
    606080ba303046049be427f4072bf446:
      image_group_id: I1GS53491
      title: ''
      volume_number: 1
      total_pages: 187
ebook_metadata:
  title: ཁྱད་དུ་འཕགས་པའི་བྱང་ཐང་ངོ་མཚར་འོས་པའི་ཐོན་ཁུངས
  author: ''
  sku: P007887
  cover: cover.jpg
  layers:
  - pagination
