id: P007887
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:47:21.145016
source_metadata:
  id: bdr:W20433
  title: ཁྱད་དུ་འཕགས་པའི་བྱང་ཐང་ངོ་མཚར་འོས་པའི་ཐོན་ཁུངས
  author: ''
  volumes:
    2419e79840944db4bc24ecd5bdbfb5ff:
      image_group_id: I1GS53491
      title: Volume 1 of khyad du 'phags pa'i byang thang ngo mtshar 'os pa'i thon
        khungs
      volume_number: 1
      total_pages: 187
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
